version: "3.9"
networks:
  bridge:
    driver: bridge
services:
  mongo:
    container_name: mongo_my_gosource
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=my_gosource
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=gosource246357
    ports:
      - 4200:27017
    networks:
      - bridge
    volumes:
      - mongo_volume:/data/db
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: redis_my_gosource
    restart: always
    volumes:
      - rediscache_volume:/data
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass 246357
    networks:
      - bridge
  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - 8080:8080
    container_name: jenkins_my_gosource
    volumes:
      - jenkins_volume:/var/jenkins_home
    networks:
      - bridge
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    container_name: elasticsearch_my_gosource
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - boostrap.memory_lock=true
      - "ES_JAVA_OPTS=9-:-Xmx2g"
      - LimitNOFILE=65536
      - LimitMEMLOCK=infinity
      - TimeoutStopSec=0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - elastic_search_volume:/usr/share/elasticsearch/data
    networks:
      - bridge
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    container_name: kibana_my_gosource
    ports:
      - 5601:5601
    networks:
      - bridge
volumes:
  mongo_volume:
  rediscache_volume:
  jenkins_volume:
  elastic_search_volume:
# docker compose -p my-gosource up -d
# docker volume ls
# docker volume rm my-gosource_rediscache_volume
# jenkins username : root - password : wQEvd@246357
