version: "3.9"
networks:
  bridge:
    driver: bridge
services:
  nginx:
    container_name: nginx_my_gosource
    restart: always
    build:
      context: ./stack-fe
    ports:
      - 3000:80
    networks:
      - bridge
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
  mongo:
    container_name: mongo_my_gosource
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=my_gosource
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=gosource246357
    ports:
      - 4200:27017
    networks:
      - bridge
    volumes:
      - mongo_volume:/data/db
    restart: unless-stopped
  backend:
    depends_on:
      - mongo
    container_name: backend_my_gosource
    build:
      context: ./stack-be
    ports:
      - 8000:8000
    environment:
      - DATABASE_PORT=4200
      - HOST=host.docker.internal
    networks:
      - bridge
  redis:
    image: redis:latest
    container_name: redis_my_gosource
    restart: always
    volumes:
      - rediscache_volume:/data
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass 246357
    networks:
      - bridge
volumes:
  mongo_volume:
  rediscache_volume:
# docker compose -p my-gosource up -d
# docker volume ls
# docker volume rm my-gosource_rediscache_volume
